consumers:
  - username: user-john

services:
  - name: mockbin-foo
    attributes:
      url: http://mockbin.com
    plugins:
      - name: rate-limiting
        ensure: "present"
        attributes:
          username: user-john
          config:
            second: 10

  - name: mockbin-bar
    attributes:
      url: http://mockbin.com

plugins:
  - name: rate-limiting
    attributes:
      username: user-john
      enabled: true
      config:
        minute: 60

  - name: rate-limiting
    attributes:
      enabled: true
      config:
        minute: 30
